"""Add cascade for url stats

Revision ID: 703296ac9af1
Revises: a4d0125881cf
Create Date: 2026-04-07 19:51:45.119444

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "703296ac9af1"
down_revision: Union[str, Sequence[str], None] = "a4d0125881cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("url_stats_url_id_fkey"), "url_stats", type_="foreignkey")
    op.create_foreign_key(
        None, "url_stats", "urls", ["url_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "url_stats", type_="foreignkey")
    op.create_foreign_key(
        op.f("url_stats_url_id_fkey"), "url_stats", "urls", ["url_id"], ["id"]
    )
    # ### end Alembic commands ###
