"""removed column redirect_elapsed_ms

Revision ID: a4d0125881cf
Revises: a0d33c25a6bd
Create Date: 2026-04-07 19:17:05.612950

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a4d0125881cf"
down_revision: Union[str, Sequence[str], None] = "a0d33c25a6bd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("url_stats", "redirect_elapsed_ms")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "url_stats",
        sa.Column(
            "redirect_elapsed_ms", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    # ### end Alembic commands ###
