apiVersion: 1

datasources:
  - name: Prometheus
    uid: ds-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus-app:9090
    isDefault: true
    editable: false

  - name: Loki
    uid: ds-loki
    type: loki
    access: proxy
    url: http://loki-app:3100
    editable: false

  - name: Jaeger
    uid: ds-jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    editable: false

  - name: Pyroscope
    uid: ds-pyroscope
    type: grafana-pyroscope-datasource
    access: proxy
    url: http://pyroscope:4040
    editable: false
